### ISSUE TITLE
Package checklist

### ISSUE THREAD

**Issue by AndreaSanchezTapia** [Model-R/modleR#11]
- [x] CITATION
- [x] README.md
- [x] LICENSE
- [x] DESCRIPTION
- [x] Version
- [x] Documentação do pacote inteiro (`R/modelr.R`)
- [x] Documentação das funções (Exemplos, description,  details, See also)
- [x] Vignette
- [x] Resolver quais dados entram no pacote e como -eles estão grandes (6MB) comprimir a 1MB.
- [x] Resolve undefined global functions or variables

**Comment by diogosbr** [comment]
Ok!
@AndreaSanchezTapia e @gmgall , como podemos dividir as tarefas para adiantar a finalização dessa lista?

**Comment by AndreaSanchezTapia** [comment]
Oi @diogosbr a maior parte disto é documentação então a divisão de tarefas não é prioritária. Esta lista é aparte da implementação e correção do pacote, isso sim seria possível dividir. Escrevi para vocês pedindo para testar e contando que buffer não está funcionando. O @gmgall apontou diferenças entre as rodadas com as duas últimas versões do pacote raster e precisamos ver exatamente em qual parte isto acontece. Acho que tudo isso tem a ver, se você puder dar uma olhada naquele email eu agradeço.

**Comment by diogosbr** [comment]
Sim eu vi. Posso testar a partir de sexta.
